-- Foreign key 

CREATE TABLE Dept
(
    D_id NUMERIC PRIMARY KEY,
    D_name VARCHAR(26) NOT NULL
);

CREATE TABLE Course
(
    c_id VARCHAR(10) PRIMARY KEY,
    c_title VARCHAR(26) NOT NULL,
    D_id NUMERIC(10) REFERENCES Dept(D_id)
    -- COLUMN LEVEL REFRENCES 
);

-- Insert values in Dept

INSERT INTO Dept
VALUES
    (1, 'Computer Science');
INSERT INTO Dept
VALUES
    (2, 'Mechanical Eng');
INSERT INTO Dept
VALUES
    (3, 'Electrical Eng');

-- Insert values in course 

INSERT INTO Course
VALUES
    ('INT306', 'DBMS', 1);
INSERT INTO Course
VALUES
    ('INT213', 'PYTHON PROGRAMMING', 1);
INSERT INTO Course
VALUES
    ('ECE213', 'DIGITAL ELECTRONIC', 3);
INSERT INTO Course
VALUES
    ('MEC107', 'ENGINEERING DRAWING', 2);


-- CHECK DATA IN TABLSE 

SELECT *
FROM DEPT;
SELECT *
FROM COURSES;


-- NESTED QUERIES: 
SELECT *
FROM DEPT
WHERE
D_ID =( SELECT D_ID
FROM COURSE
WHERE C_ID = 'INT213');


-- TABLE LEVEL REFRENCING 

-- FIRST CREATE A TABLE WITHOUT ANY CONSTRAINTS 
-- THEN ADD CONSTRAINTS 

CREATE TABLE TEMP (
    ROLL NUMERIC(10), 
    C_NAME VARCHAR(20), 
    PRIMARY KEY (ROLL)
);

-- DROP TABLE TEMP;

CREATE TABLE TEMP (
    ROLL NUMERIC(10), 
    C_NAME VARCHAR(20), 
    PRIMARY KEY (ROLL),
    UNIQUE (C_NAME, COLUMN1, COLUMN2, SO_oN) 
    -- CREATE AN OBJECT OF CONSTRAINT, NAME IT AS PK 
    -- NAME OF OBJECT MUST BE UNIQUE 
);

CREATE TABLE TEMP (
    ROLL NUMERIC(10), 
    C_NAME VARCHAR(20), 
    CONSTRAINT PK PRIMARY KEY (ROLL),
    CONSTRAINT UK UNIQUE (C_NAME, COLUMN1, COLUMN2, SO_ON) 
    -- CREATE AN OBJECT OF CONSTRAINT, NAME IT AS PK 
    -- NAME OF OBJECT MUST BE UNIQUE 
);



