-- TABLE LEVEL REFRENCING 

-- FIRST CREATE A TABLE WITHOUT ANY CONSTRAINTS 
-- THEN ADD CONSTRAINTS 

CREATE TABLE TEMP (
    ROLL NUMERIC(10), 
    C_NAME VARCHAR(20), 
    PRIMARY KEY (ROLL)
);

-- DROP TABLE TEMP;

CREATE TABLE TEMP (
    ROLL NUMERIC(10), 
    C_NAME VARCHAR(20), 
    PRIMARY KEY (ROLL),
    UNIQUE (C_NAME, COLUMN1, COLUMN2, SO_oN) 
    -- CREATE AN OBJECT OF CONSTRAINT, NAME IT AS PK 
    -- NAME OF OBJECT MUST BE UNIQUE 
);

CREATE TABLE TEMP (
    ROLL NUMERIC(10), 
    C_NAME VARCHAR(20), 
    CONSTRAINT PK PRIMARY KEY (ROLL),
    CONSTRAINT UK UNIQUE (C_NAME, COLUMN1, COLUMN2, SO_ON) 
    -- CREATE AN OBJECT OF CONSTRAINT, NAME IT AS PK 
    -- NAME OF OBJECT MUST BE UNIQUE 
);

-- tABLE LEVEL CONSTRAINT: CHECK
CREATE TABLE TEMP(
    ROLL NUMERIC(10), 
    S_NAME VARCHAR(25), 
    AGE NUMERIC(2),
    CHECK(AGE > 18),
    PRIMARY KEY(ROLL)
);

-- TABLE LEVEL CONSTRAINT USING KEYWORD CONSTRAINT
CREATE TABLE TEMP(
    ROLL NUMERIC(10), 
    S_NAME VARCHAR(25), 
    AGE NUMERIC(2),
    PRIMARY KEY(ROLL),
    
    CONSTRAINT AGECHECK CHECK(AGE > 18),
);

-- fOREIGN KEY USING TABLE LEVEL
CREATE TABLE COURSE (
    C_ID VARCHAR(34),
    C_NAME VARCHAR(33),
    D_ID VARCHAR(43),
    FOREIGN KEY (D_ID) REFERENCES DEPT(D_ID)
);

-- fOREIGN KEY USING TABLE LEVEL AND CONSTRAINT KEYWORD 
CREATE TABLE COURSE (
    C_ID VARCHAR(45), 
    C_NAME VARCHAR(33), 
    D_ID VARCHAR(33), 
    CONSTRAINT FK FOREIGN KEY(D_ID) REFERENCES DEPT(D_ID)
);

-- NOT NULL USING TABLE LEVEL CONSTRAINT : NOT ALLOWED
CREATE TABLE COURSE (
    C_ID VARCHAR(45) PRIMARY KEY, 
    C_NAME VARCHAR(33), 
    D_ID VARCHAR(33),

    UNIQUE (C_NAME),
    CONSTRAINT FK FOREIGN KEY (D_ID) REFERENCES DEP(D_ID)
);


-- aDD CONSTRAINTS IN EXISTING TABLE 

-- ADD PRIMARY KEY IN EXISTING TABLE 
-- ALTER TABLE T_NAME ADD PRIMARY KEY (C_NAME);

-- cASE1: DATA EXISTS 
    -- 1. UNIQUE DATA 
    -- 2. DUPLICATE DATA 
-- CASE2: DATA DOES NOT EXITST 

CREATE TABLE TEMP (
    ROLL NUMERIC(2), 
    NAME VARCHAR(12)
);

-- DATA DOES NOT EXIST, SO NO ERROR 
ALTER TABLE TEMP ADD PRIMARY KEY(ROLL);

-- DROP TEMP;

-- ADD DATA DUPLICATE 
INSERT INTO TEMP VALUES (1, 'DSF');
INSERT INTO TEMP VALUES (1, 'DSAF');
INSERT INTO TEMP VALUES (2, 'DSE');

-- ALTER TABLE TEMP ADD PRIMARY KEY(ROLL); 
-- eRROR SINCE COLUMN CONTAINS DUPLICATE VALUES 

