CREATE TABLE TEACHER
(
    T_ID NUMERIC(3) PRIMARY KEY,
    T_NAME VARCHAR(30) NOT NULL,
    CITY VARCHAR(20),
    SALARY NUMERIC(12),
    BRANCH VARCHAR(20)
);

INSERT INTO TEACHER
VALUES
    (0, 'ABD', 'X', 32342, 'J');
INSERT INTO TEACHER
VALUES
    (1, 'SGG', 'Y', 45345, 'L');
INSERT INTO TEACHER
VALUES
    (2, 'SRG', 'X', 23466, 'J');
INSERT INTO TEACHER
VALUES
    (3, 'YHF', 'X', 13256, 'L');
INSERT INTO TEACHER
VALUES
    (4, 'IHT', 'Y', 65343, 'P');

SELECT *
FROM TEACHER;

SELECT CITY
FROM TEACHER;

-- TO AVOID DUPLICATE : DISTINCT IS USED WITH COLUMN

SELECT DISTINCT CITY
FROM TEACHER;

-- PRINTS UNIQUE CITIES 

-- IF WE COMBINE DIFFERENT ROWS , IT WILL SHOW UNIQUE COMBINATIONS
-- OF SELECTED ROWS 

SELECT DISTINCT CITY, BRANCH FROM TEACHER;

-- TO SORT THE QUERY OUTPUT: ORDER BY IS USED 
-- ASC - ASCENDING ORDER 
-- DESC - DESCENDING ORDER 

-- ACTUAL DATA IS NOT REARRANGED ONLY THE OUTPUT IS SORTED. 
-- SORTING IS DONE ON A SPECIFIC COLUMN 

-- ASCENDING SORT ON SALARY 
SELECT * FROM TEACHER ORDER BY SALARY ASC;

-- DESCENDING SORT ON SALARY 
SELECT * FROM TEACHER ORDER BY SALARY DESC;

-- NESTED ORDER 
-- SORT AFTER SORT 
SELECT * FROM TEACHER ORDER BY SALARY DESC, CITY DESC;

-- BY DEFAULT ORDER IS ASCENDING ORDER 

-- ALias  IS USED TO RENAME THE COLUMN NAME IN QUERY OUTPUT ONLY
-- THE STRUCTURE OF TABLE REMAINS THE SAME ;

SELECT SALARY CTC, BRANCH OFFICE FROM TEACHER;

-- OTHER WAYS TO CREATE ALIAS 
-- USING DOUBLE QUOTE FOR ALIAS NAME 

SELECT CITY "BRANCH" FROM TEACHER; 

-- USE AS KEYWORD TO DESCRIBE ALIAS NAME 

SELECT CIYT AS COUNTRY FROM TEACHER ;

-- BETWEEN OPERATOR IS USED TO SELECT DATA FROM A RANGE ;
-- WHERE SALARY BETWEEN LL AND UL;
-- LIMITS ARE INCLUSIVE ;

SELECT * FROM TEACHER WHERE SALARY BETWEEN 10000 AND 40000;

-- ARITHERMETIC OPERATOR 
-- NAME OF THE COLUMN IS CHANGED TO SALARY * 2 IN OUTPUT 
SELECT SALARY * 2 FROM TEACHER;
SELECT SALARY + 2000 FROM TEACHER;

-- USE CASE OF ALIAS, WE CAN USE ALIAS TO HIDE DETAILS OF OPERATION 
SELECT SALARY * 2 AS NEWSALARY FROM TEACHER; 

-- DUAL TABLE IS AN INBUILT TABLE USED TO FACILITATE QUERIES INDEPENDENT OF 
-- ANY TABLE 

SELECT 3 * 324 FROM DUAL;
-- AGAIN THE NAME OF COLUMN WILL BE SAME AS OPERATION 
-- USE ALIAS TO CHANGE NAME     

-- SYSDATE 
SELECT SYSDATE "TODAYSDAY" FROM TEACHER;

-- LIKE OPERATOR : USED FOR STRING OR PATTERN MATCHING 
-- MATCHES ONE STRING TO ANOTHER 

-- TWO WILD CARD CHARACTERS ARE USED 

-- PERCENT (%): CHARACTER TO MATCH ANY STRING OF ANY LENGTH (0-N)
-- UNDERSCORE (_): CHARACTER TO A SINGLE CHARACTER. 

-- STRINGS MATCHING IS CASE SENSITIVE ;

-- NAME STARTING WITH A 
SELECT T_NAME FROM TEACHER WHERE NAME LIKE "A%";

-- NAME ENDING WITH A
SELECT T_NAME FROM TEACHER WHERE NAME LIKE 'A%';

-- SUBSTRING IS A 
SELECT T_NAME FROM TEACHER WHERE NAME LIKE "%A%";

-- SECOND LETTER A 
SELECT T_NAME FROM TEACHER WHERE NAME LIKE "_A%";

-- SECOND LAST LETTER A 
SELECT T_NAME FROM TEACHER WHERE NAME LIKE "%A_";

-- NAME WITH LENGTH 5
SELECT T_NAME FROM TEACHER WHERE NAME LIKE "_____";

-- AT LEAST TWO LENGTH 
SELECT T_NAME FROM TEACHER WHERE NAME LIKE "__%";