-- char(size) upto 255 chars ;
-- varchar(size)/varchar2(size) upto 4000 char 
-- date DD-Mon-YYYY
-- NUMBER (10, 2): NUMBER OF DECIMAL DIGITS : 2 

-- Set operations syntax: 

-- select - statement1 
-- UNION/INTERSECTION/MINUS
-- SELECT STATEMENT2;

-- CREATE TABLE ACCOUNT 
CREATE TABLE ACCOUNT (
    A_NAME VARCHAR(20),
    AMOUNT NUMERIC(19)
);

-- CREATE TABLE COLUMN
CREATE TABLE LOAN (
    A_NAME VARCHAR(20), 
    L_NO NUMERIC
);

INSERT INTO ACCOUNT VALUES ('A', 100); 
INSERT INTO ACCOUNT VALUES ('B', 200);
INSERT INTO ACCOUNT VALUES ('C', 300); 

INSERT INTO LOAN VALUES ('C', 1); 
INSERT INTO LOAN VALUES ('D', 2); 
INSERT INTO LOAN VALUES ('E', 3); 


-- NAME OF ALL THE CUSTOMER WHO EITHER HAVE LOAN OR HAVE AN ACCOUNT
-- USE UNION SELECT 
SELECT A_NAME FROM ACCOUNT UNION SELECT A_NAME FROM LOAN;

-- NAME OF ALL THE CUSTOMER WHO HAVE BOTH LOAN AND ACCOUNT 
-- USE INTERSECT KEYWORD 
SELECT A_NAME FROM ACCOUNT INTERSECT SELECT A_NAME FROM LOAN;

-- NAME OF ALL THE CUSTOMER WHO DON'T HAVE LOAN 
SELECT A_NAME FROM ACCOUNT MINUS SELECT A_NAME FROM LOAN;