-- FUNCTION WHICH TAKES N NUMBER OF INPUT AND GIVES ONE OUTPUT 

-- FOLLWING ARE THE AGGREGATE FUNCTION: 
-- AVG
-- MIN
-- MAX 
-- SUM 
-- COUNT 

-- AVG 
SELECT AVG(SALARY) FROM TEACHER;

-- MIN 
SELECT MIN(SALARY) FROM TEACHER;

-- MAX
SELECT MAX(SALARY) FROM TEACHER;

-- SUM
SELECT SUM(SALARY) FROM TEACHER;

-- COUNT: tWO WAYS OF USING THE COUNT 

-- COUNTS THE NUMBER OF ENTRIES IN A COLUMN EXCLUDING NULL 
SELECT COUNT(SALARY) FROM TEACHER;
-- COUNTS THE NUMBER OF ROWS IN TABLE 
SELECT COUNT(*) FROM TEACHER;
