-- It creates a data set that contains several set of records grouped 
-- together based on a condition 

-- syntax 

SELECT BRANCH, COUNT(T_ID)
FROM TEACHER
GROUP BY BRANCH;

-- Having : ONLY USED WITH GROUP BY 

SELECT BRANCH, COUNT(CITY)
FROM TEACHER
GROUP BY BRANCH
HAVING BRANCH = 'L';


-- FIRST GROUP IS FORMED AND THEN CONDITION IS APPLIED IN 
-- HAVING WHERE AS IN WHERE CONDITION IS APPLIED FIRST AND THEN
-- GROUPING IS DONE 

-- WE CAN USE HAVING AND WHERE SIMULTANEOUSLY 

SELECT BRANCH, COUNT(CITY)
FROM TEACHER 
WHERE CITY = 'X'
GROUP BY BRANCH 
HAVING BRANCH = 'P' OR BRANCH = 'J';

-- WHERE IS APPLIED ON TUPLE(ROW), HAVING IS APPLIED ON GROUP(COLUMN)