-- OPERATION PRIVLAGES TO BE DEFINED; 

-- ALTER
-- DELETE
-- INSERT
-- SELECT
-- UPDATE
-- INDEX
-- WITH GRANT OPTION 

-- GRANT: THE OWNER OF DATABASE OBJECT CAN GRANT THE PRIVLEGES 
-- TO A USER BY USING GRANT COMMAND. THE DATABASE OBJECT CAN BE A TABLE, 
-- A VIEW OR A SEQUENCE. 

-- SYNTAX 
-- GRANT PRIVILEGES 
--     ON OBJECT NAME 
--     TO USER_NAME
--     WITH GRANT OPTION 

-- OBJECT CAN BE TABLE, VIEW, ETC
-- WITH GRANT OPTIONS ENABLES THE USER TO GRANT PERMISSIONS TO FURTHER
-- USERS. LIKE GETTING ADMIN/MOD ABILITIES 

GRANT DELETE, UPDATE
ON TEACHER
TO USER_NAME
WITH GRANT OPTION;

-- REVOKE 
-- THE PRIVILEGES GRANTED TO A USER CAN BE REVOKED (TAKEN BACK) WITH REVOKE 
-- COMMAND

-- SYNTAX 
-- REVOKE PRIVILEGES
-- ON OBJECT NAMES
-- FROM USER_NAME

REVOKE DELETE 
ON TEACHER 
FROM USER_NAME

-- Two types of privileges 

-- 1. System Privileges 
--   create system 
--   create table
--   create view 
--   create synonyms 

-- 2. Object privileges
--      insert 
--      delete
--      update 

-- Syntax to create user 
-- create user userName identified by password;

-- CREATE USER 'sudo'@'localhost' IDENTIFIED BY 'password'; 

-- grant privileges to sudo 
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'sudo'@'localhost';


`