-- A VIEW IS AN IMAGINARY TABLE THAT IS CREATED FROM SOME OTHER 
-- BASE TABLE 

-- SYNTAX: 
-- CREATE VIEW VIEWNAME
-- AS SELECT COLUMN LIST 
-- FROM TABLE NAME 
-- WHERE CONDITION 

-- IT DOES NOT OCCUPY ANY EXTRA MEMORY 
-- CREATE VIEW STUDENT_VIEW AS SELECT T_NAME, CITY, BRANCH FROM TEACHER;

-- STUDENT VIEW IS LISTED AS A NEW TABLE, BUT IT IS JUST IMAGINARY 
-- IT DOES NOT TAKE ANY MEMORY ON THE DISC 

-- HOW EVER IF WE UPDATE ANY DATA IN CREATED VIEW, THE CHANGES WILL BE REFELECTED
-- IN THE MAIN TABLE 

-- DROP VIEW VIEWNAME
-- DROP VIEW STUDENT_VIEW;

-- UPDATING VALUES IN VIEW 
UPDATE STUDENT_VIEW SET T_NAME = 'AVI' WHERE CITY = 'Y';

SELECT * FROM STUDENT_VIEW;
SELECT * FROM TEACHER;

-- DATA IS CHANGED IN BOTH TABLES; 