-- Create table dept and hod 

CREATE TABLE DEPT(
    D_ID NUMERIC PRIMARY KEY, 
    D_NAME VARCHAR(26)
);

CREATE TABLE HOD (
    H_ID NUMERIC PRIMARY KEY, 
    H_NAME VARCHAR(26), 
    D_ID NUMERIC REFERENCES DEPT(D_ID)
);

INSERT INTO DEPT VALUES(1, 'CSE');
INSERT INTO DEPT VALUES(2, 'ME');
INSERT INTO DEPT VALUES(3, 'ECE');
INSERT INTO DEPT VALUES(4, 'CE');

INSERT INTO HOD VALUES(1, 'ABC', 2);
INSERT INTO HOD VALUES(2, 'XYZ', 1);
INSERT INTO HOD VALUES(3, 'PQR', 3);
INSERT INTO HOD VALUES(4, 'MNO', 4);


-- cARTESIAN PRODUCT (CROSS JOIN)
SELECT * FROM DEPT, HOD;

-- CARTISIAN PRODUCT WITH LIMITED COLUMN 
SELECT D_NAME, H_NAME FROM DEPT, HOD;

-- INCORRECT QUERY
-- SELECT DISTINCT D_NAME, H_NAME FROM DEPT, HOD;


-- iNNER JOIN: ONLY THE ROWS WITH MATCHING COMMON ATTRIBUTE
SELECT * FROM DEPT, HOD
WHERE HOD.D_ID = DEPT.D_ID;

-- SHOW DEPT NAME AND RESPECTIVE HOD NAME 
SELECT D_NAME, H_NAME FROM DEPT, HOD
WHERE HOD.D_ID = DEPT.D_ID;

-- oUTER JOINS ARE USED TO INCLUDE THE VALUE WHICH ARE NOT MATCHING 

INSERT INTO DEPT VALUES(5, 'CHE');

INSERT INTO HOD (H_ID, H_NAME) VALUES(5, 'SFD');

-- LEFT OUTER JOIN 

-- eRROR: SINCE TABLES ARE NOT COMPATIBLE 
-- SELECT D_NAME, H_NAME FROM DEPT, HOD
-- WHERE HOD.D_ID = DEPT.D_ID 
-- UNION
-- SELECT D_NAME FROM DEPT;

-- LEFT OUTER 

SELECT D_NAME, H_NAME FROM DEPT LEFT JOIN HOD
ON HOD.D_ID = DEPT.D_ID;

-- RIGHT OUTER
SELECT D_NAME, H_NAME FROM DEPT RIGHT JOIN HOD
ON HOD.D_ID = DEPT.D_ID;

-- CREATE TABLE EMP

CREATE TABLE EMP(
    ID NUMERIC (10), 
    E_NAME VARCHAR(34), 
    HOD NUMERIC(4)
);

INSERT INTO EMP VALUES (1, 'M', 2);
INSERT INTO EMP VALUES (3, 'O', 4);
INSERT INTO EMP (ID, E_NAME) VALUES (2, 'N');
INSERT INTO EMP (ID, E_NAME) VALUES (4, 'P');

-- SELF JOIN 

-- ERROR: DUPLICATE/ALIAS 
-- SELECT E_NAME, HOD FROM EMP, EMP 
-- WHERE EMP.HOD = EMP.ID;

-- SELF JOIN
SELECT EMP.E_NAME, AMP.HOD FROM EMP, AMP 
WHERE EMP.ID = AMP.HOD;

