-- create table: emp 
CREATE TABLE EMPLOYEE
(
    E_ID NUMERIC(10) PRIMARY KEY,
    E_NAME VARCHAR (30) NOT NULL,
    D_NO NUMERIC(10),
    D_NAME VARCHAR (20),
    JOB VARCHAR(20),
    SALARY NUMERIC(10)
);

INSERT INTO EMPLOYEE
VALUES(21, 'SHUBH', 1, 'CSE', 'CLERK', 32444);
INSERT INTO EMPLOYEE
VALUES(22, 'AVI', 2, 'MEC', 'CLERK', 43233);
INSERT INTO EMPLOYEE
VALUES(23, 'AVESH', 3, 'ECE', 'CLERK', 45344);
INSERT INTO EMPLOYEE
VALUES(24, 'TUS', 4, 'CHE', 'TEACHER', 54233);
INSERT INTO EMPLOYEE
VALUES(25, 'AJI', 1, 'CSE', 'TEACHER', 54344);
INSERT INTO EMPLOYEE
VALUES(26, 'UDAY', 2, 'MEC', 'TEACHER', 76455);
INSERT INTO EMPLOYEE
VALUES(27, 'VIDIT', 3, 'ECE', 'AO', 43534);
INSERT INTO EMPLOYEE
VALUES(28, 'BOSE', 4, 'CHE', 'AO', 45344);
INSERT INTO EMPLOYEE
VALUES(29, 'SK', 1, 'CSE', 'AO', 64534);
INSERT INTO EMPLOYEE
VALUES(31, 'BAROD', 4, 'CHE', 'AO', 23544);
INSERT INTO EMPLOYEE
VALUES(32, 'JAS', 3, 'ECE', 'TEACHER', 76543);
INSERT INTO EMPLOYEE
VALUES(33, 'GUH', 2, 'MEC', 'CLERK', 32534);


-- SELECT EMP NAME WITH THEIR DEPT 
SELECT E_NAME, D_NAME
FROM EMPLOYEE;

-- SELECT THE NAME OF THE EMPLOYEE WHO ARE EARNING MORE THAN 40000
SELECT E_NAME
FROM EMPLOYEE
WHERE SALARY > 40000;

-- SELECT THE DETAILS OF EMP WHO ARE EARNING MORE THAN 40K
SELECT *
FROM EMPLOYEE
WHERE SALARY > 40000; 

-- Find the total salary for each of the departmenet 
SELECT D_NAME, SUM(SALARY)
FROM EMPLOYEE
GROUP BY D_NAME;

-- fIND THE AVG SALARY FOR EACH JOB 
SELECT JOB, AVG(SALARY)
FROM EMPLOYEE
GROUP BY JOB;

-- FIND THE TOTAL SALARY FOR EACH JOB WITHIN EACH DEPT 
SELECT D_NAME, JOB, SUM(SALARY)
FROM EMPLOYEE
GROUP BY D_NAME, JOB;

SELECT JOB, D_NAME, SUM(SALARY)
FROM EMPLOYEE
GROUP BY JOB, D_NAME ORDER BY D_NAME;

-- FIND THE NAME OF THE EMPLOYEE WHO ARE WORKING AS A CLERK IN CSE DEPT

SELECT E_NAME
FROM EMPLOYEE
GROUP BY JOB, D_NAME
HAVING JOB = 'CLERK' AND D_NAME = 'CSE';

-- OR WE CAN USE WHERE CLAUSE 

-- I WANT TO SEE THE NAMES OF THE DEPT THAT I HAVE 
SELECT DISTINCT D_NAME FROM EMPLOYEE;

-- FIND EACH DEPT_NUMBER OF NUMBER OF EMPLOYEE IN THAT DEPT 
SELECT D_NO, COUNT(D_NO)
FROM EMPLOYEE
GROUP BY D_NO;

-- FIND THE DEPT NUMBER AND MAX SALARY OF THE DEPTS WHICH HAS MAX SALARY OF MORE THAN 50K
SELECT D_NO, MAX(SALARY)
FROM EMPLOYEE
GROUP BY D_NO
HAVING MAX(SALARY) > 60000;

-- FIND THE JOB AND MIN SALARY OF EACH JOB FOR DEPT NO 1, BUT DISPLAY ONLY THOSE 
-- THAT HAVE MAX SALARY MORE THAN 50000;

SELECT JOB, MIN(SALARY)
FROM EMPLOYEE 
WHERE D_NO = 1
GROUP BY JOB
HAVING MAX(SALARY) > 50000;