-- Create user table 
CREATE TABLE USERS (
    U_ID NUMERIC(10) PRIMARY KEY, 
    PASS VARCHAR(20) NOT NULL, 
    FIRST_NAME VARCHAR(30), 
    LAST_NAME VARCHAR(30), 
    GENDER VARCHAR(10), 
    AGE NUMERIC(3), 
    AADHAR_NUMBER NUMERIC(16) UNIQUE,
    EMAIL VARCHAR(30) UNIQUE, 
    MOBILE_NUMBER NUMERIC(10)
);

-- create station table 
CREATE TABLE STATION (
    ST_ID NUMERIC(10) PRIMARY KEY, 
    ST_NAME VARCHAR(30) NOT NULL,
    ST_STATE VARCHAR(30), 
    CATEGORY VARCHAR(10)
);

CREATE TABLE TRAIN (
    T_ID NUMERIC(10) PRIMARY KEY, 
    T_NAME VARCHAR(30) NOT NULL, 
    STARTS_AT VARCHAR(30),
    ENDS_AT VARCHAR(30)
);

CREATE TABLE TRAIN_STATUS (
    T_ID NUMERIC(10) PRIMARY KEY, 
    A_SEATS NUMERIC(10),
    B_SEATS NUMERIC(10),
    C_SEATS NUMERIC(10)
);

CREATE TABLE TICKET (
    TICKET_ID NUMERIC(10) PRIMARY KEY, 
    BOOKED_BY NUMERIC(10) REFERENCES USERS(U_ID),
    PASSENGER_COUNT NUMERIC(10), 
    TRAIN_ID NUMERIC(10) REFERENCES TRAIN(T_ID),
    RESERVATION_STATUS VARCHAR(20),
    SOURCE VARCHAR(30), 
    DESTINATION VARCHAR(30)
);

CREATE TABLE PASSENGER (
    PASSENGER_ID NUMERIC(10) PRIMARY KEY, 
    PSG_NAME VARCHAR(30), 
    GENDER VARCHAR(10), 
    AGE NUMERIC(3), 
    SOURCE VARCHAR(30), 
    DESTINATION VARCHAR(30),
    PNR_NO NUMERIC(20), 
    SEAT_NO NUMERIC(10), 
    TICKET_ID NUMERIC(10) REFERENCES TICKET(TICKET_ID)
);

-- CREATE RELATION TABLES 

CREATE TABLE CANCELS (
    U_ID NUMERIC(10) REFERENCES USERS(U_ID), 
    TICKET_ID NUMERIC(10) REFERENCES TICKET(TICKET_ID),
    PASSENGER_ID NUMERIC(10) REFERENCES PASSENGER(PASSENGER_ID)
);

CREATE TABLE BOOKS (
    U_ID NUMERIC(10) REFERENCES USERS(U_ID), 
    TICKET_ID NUMERIC(10) REFERENCES TICKET(TICKET_ID)
);

CREATE TABLE STARTS (
    TRAIN_ID NUMERIC(10) REFERENCES TRAIN(T_ID), 
    ST_ID NUMERIC(10) REFERENCES STATION (ST_ID)
);

CREATE TABLE STOPS_AT (
    TRAIN_ID NUMERIC(10) REFERENCES TRAIN(T_ID), 
    ST_ID NUMERIC(10) REFERENCES STATION (ST_ID)
);

CREATE TABLE REACHES (
    TRAIN_ID NUMERIC(10) REFERENCES TRAIN(T_ID), 
    ST_ID NUMERIC(10) REFERENCES STATION (ST_ID),
    TIMING DATETIME(6)
);