-- CREATE OR REPLACE TRIGGER TRIGGERnAME
--     BEFORE/AFTER 
--     DELETE/INSERT/UPDATE OF COLUMNnAME
--     ON TABLEnAME
--         REFRENCING OLD AS OLD, NEW AS NEW
--         FOR EACH ROW 
--         WHEN CONDITION()
-- DECLARE 
--     VARIABLE AND CONSTANT DECLARATION;
-- BEGIN 
--     SQL AND PL/SQL STATEMENTS;
-- EXCEPTION 
--     ERROR HANDLING STATEMENT;
-- END;

CREATE TABLE T21 (
    SNAME VARCHAR(21)
);

CREATE TRIGGER DISPLAYSTATEMENT
    AFTER INSERT ON T21
BEGIN
    DBMS_OUTPUT.PUT_LINE('DATA IS INSERTED SUCCESSFULLY');
END;


-- TEST TRIGGER 
INSERT INTO T21 VALUES ('AVESH SINGH');


-- CREATING MULTIPLE ROUTES IN A SINGLE TRIGGER 
CREATE OR REPLACE TRIGGER MULTIPURPOSE 
    BEFORE 
    UPDATE OR INSERT OR DELETE ON T21 
BEGIN 
    IF INSERTING THEN 
        DBMS_OUTPUT.PUT_LINE('DATA IS BEING INSERTED');
    ELSIF DELETING THEN 
        DBMS_OUTPUT.PUT_LINE('DATA IS BEING DELETED');
    ELSE
        DBMS_OUTPUT.PUT_LINE('DATA IS BEING UPDATED');
    END IF;
END;

-- drop TRIGGER trigername;

-- alter triger trigername disable;
-- trigger is not dropped just turned off for the moment;

-- alter table tablename disable all trigger;

-- alter table tablename enable all trigger;
-- alter table tablename enable triggername;