DECLARE 
    SAL EMP.SALARY%TYPE
    JOB EMP.JOB%TYPE 
    ID EMP.ID%TYPE
    CURSOR NEW_CURSOR IS SELECT E_ID, JOB, SALARY FROM EMP;
BEGIN 
    OPEN NEW_CURSOR;
    LOOP 
        FETCH NEW_CURSOR INTO ID, JOB, SAL;
        EXIT WHEN NEW_CURSOR%NOTFOUND;

        SAL := SAL + 1000;
        IF JOB = 'ENG' THEN 
            UPDATE EMP SET SALARY = SAL WHERE E_ID = ID;
        END IF;
    END LOOP;

    CLOSE NEW_CURSOR;
END;