-- Creating a stored procedure 

CREATE OR REPLACE PROCEDURE DIFFER (NUM1 IN NUMBER, NUM2 IN NUMBER, DIFF OUT NUMBER) IS 
    BEGIN
        DIFF := NUM2 - NUM1;
    END;

DECLARE 
    NUM1 NUMBER (10);
    NUM2 NUMBER (10);
    DIF NUMBER (10);

BEGIN 
    NUM1 := 21333;
    NUM2 := 43233;
    DIFFER (NUM1, NUM2, DIF);
    DBMS_OUTPUT.PUT_LINE(DIF);
END ;