-- WRITE A PROGRAM TO FIND THE FACTORIAL OF A NUMBER 

DECLARE 
    NUM NUMBER (10);
    FACTO NUMBER (20);

    FUNCTION FIND_FACTORIAL (NUM1 IN NUMBER) RETURN NUMBER IS 
        BEGIN 
            -- PRINT THE NUM FOR WHICH WE CAN 
            DBMS_OUTPUT.PUT_LINE(NUM1);
            IF (NUM1 < 2) THEN 
                RETURN 1;
            END IF;

            RETURN NUM1 * FIND_FACTORIAL(NUM1-1);
        END FIND_FACTORIAL;
    
BEGIN
    NUM := 21;
    DBMS_OUTPUT.PUT_LINE(FIND_FACTORIAL(NUM));
END;